# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2951dd6c51c5cdadca78b259c5261c969ac7a33b6f70d5de99d6f1a9ae7d7fc247296f33f73a26d5df68ba9fcbbb413059355d07e0f309871a28252f238eb5e9

test:
  secret_key_base: 9b2a53a7e8eb195d14d6689427cafeec5f826256f5771cd954324792d50d41766aae7e9ad670f019b4c1ba7f6bf568b03506396ea59b8826c6ae425c2600afd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
